BEGIN TRANSACTION;

INSERT INTO Employees
VALUES (8,'Kevin','Finance',70000);

SAVE TRANSACTION SavePoint1;

INSERT INTO Employees
VALUES (9,'Chris','IT',90000);

ROLLBACK TRANSACTION SavePoint1;

COMMIT TRANSACTION;

SELECT * FROM Employees;